# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-02-05 15:08
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Harvest',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Nome da Colheita')),
                ('initial_date', models.DateField(verbose_name='Data Inicial da Colheita')),
                ('final_date', models.DateField(verbose_name='Data Final da Colheita')),
            ],
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True, verbose_name='Nome do Produto')),
                ('average_cost', models.DecimalField(blank=True, decimal_places=2, max_digits=15, null=True, verbose_name='Custo M\xe9dio do Produto (R$)')),
            ],
        ),
        migrations.CreateModel(
            name='Service',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Nome do Servi\xe7o')),
                ('initial_date', models.DateField(verbose_name='Data Inicial do Servi\xe7o')),
                ('final_date', models.DateField(verbose_name='Data Final do Servi\xe7o')),
                ('harvest', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='harvests', to='API.Harvest', verbose_name='Colheita')),
            ],
        ),
        migrations.CreateModel(
            name='ServiceProduct',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.DecimalField(blank=True, decimal_places=2, max_digits=15, null=True, verbose_name='Quantidade do Produto no Servi\xe7o (Kg)')),
                ('total_cost', models.DecimalField(blank=True, decimal_places=2, max_digits=15, null=True, verbose_name='Custo Total do Produto no Servi\xe7o (R$)')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='service_products', to='API.Product')),
                ('service', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='service_products', to='API.Service')),
            ],
        ),
    ]
